# Generated by Django 4.1 on 2022-09-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=200)),
                ('pdesc', models.TextField()),
                ('ppic', models.CharField(max_length=120)),
                ('giturl', models.CharField(max_length=500)),
            ],
        ),
    ]
